version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    ports:
     - 22123:22
    volumes:
      - ./workspaces:/home/user/ws
      - ./ssh:/etc/ssh
    links:
     - db
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - .env
    command: postgres -c log_statement=all
