version: "3.7"

services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    env_file: 
      - ./.devcontainer/.env
    init: true
  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - ./.devcontainer/.env
    ports:
      - 5432:5432

volumes:
  postgres-data: